"""amplifier-ipc-protocol: Canonical event constants for the Amplifier IPC protocol.

Single source of truth for all event name strings.  Compatible with the
``amplifier_core.events`` module naming convention.

Usage::

    from amplifier_ipc_protocol import SESSION_START, CONTENT_BLOCK_START
    from amplifier_ipc_protocol.events import TOOL_PRE, TOOL_POST
"""

from amplifier_ipc_protocol.events import (
    APPROVAL_DENIED,
    APPROVAL_GRANTED,
    APPROVAL_REQUIRED,
    ARTIFACT_READ,
    ARTIFACT_WRITE,
    CANCEL_COMPLETED,
    CANCEL_REQUESTED,
    CONTENT_BLOCK_DELTA,
    CONTENT_BLOCK_END,
    CONTENT_BLOCK_START,
    CONTEXT_COMPACTION,
    CONTEXT_INCLUDE,
    CONTEXT_POST_COMPACT,
    CONTEXT_PRE_COMPACT,
    DELEGATE_AGENT_COMPLETED,
    DELEGATE_AGENT_RESUMED,
    DELEGATE_AGENT_SPAWNED,
    DELEGATE_ERROR,
    EXECUTION_END,
    EXECUTION_START,
    LLM_REQUEST,
    LLM_RESPONSE,
    ORCHESTRATOR_COMPLETE,
    PLAN_END,
    PLAN_START,
    POLICY_VIOLATION,
    PROMPT_COMPLETE,
    PROMPT_SUBMIT,
    PROVIDER_ERROR,
    PROVIDER_REQUEST,
    PROVIDER_RESOLVE,
    PROVIDER_RESPONSE,
    PROVIDER_RETRY,
    PROVIDER_THROTTLE,
    PROVIDER_TOOL_SEQUENCE_REPAIRED,
    SESSION_END,
    SESSION_FORK,
    SESSION_RESUME,
    SESSION_START,
    THINKING_DELTA,
    THINKING_FINAL,
    TOOL_ERROR,
    TOOL_POST,
    TOOL_PRE,
    USER_NOTIFICATION,
)

__all__ = [
    # Session Lifecycle
    "SESSION_START",
    "SESSION_END",
    "SESSION_FORK",
    "SESSION_RESUME",
    # Prompt
    "PROMPT_SUBMIT",
    "PROMPT_COMPLETE",
    # Planning
    "PLAN_START",
    "PLAN_END",
    # Provider
    "PROVIDER_REQUEST",
    "PROVIDER_RESPONSE",
    "PROVIDER_RETRY",
    "PROVIDER_ERROR",
    "PROVIDER_THROTTLE",
    "PROVIDER_TOOL_SEQUENCE_REPAIRED",
    "PROVIDER_RESOLVE",
    # LLM
    "LLM_REQUEST",
    "LLM_RESPONSE",
    # Content Blocks
    "CONTENT_BLOCK_START",
    "CONTENT_BLOCK_DELTA",
    "CONTENT_BLOCK_END",
    # Thinking
    "THINKING_DELTA",
    "THINKING_FINAL",
    # Tools
    "TOOL_PRE",
    "TOOL_POST",
    "TOOL_ERROR",
    # Context
    "CONTEXT_PRE_COMPACT",
    "CONTEXT_POST_COMPACT",
    "CONTEXT_COMPACTION",
    "CONTEXT_INCLUDE",
    # Orchestrator
    "ORCHESTRATOR_COMPLETE",
    "EXECUTION_START",
    "EXECUTION_END",
    # User
    "USER_NOTIFICATION",
    # Artifacts
    "ARTIFACT_WRITE",
    "ARTIFACT_READ",
    # Policy / Approvals
    "POLICY_VIOLATION",
    "APPROVAL_REQUIRED",
    "APPROVAL_GRANTED",
    "APPROVAL_DENIED",
    # Cancellation
    "CANCEL_REQUESTED",
    "CANCEL_COMPLETED",
    # Delegate
    "DELEGATE_AGENT_SPAWNED",
    "DELEGATE_AGENT_COMPLETED",
    "DELEGATE_AGENT_RESUMED",
    "DELEGATE_ERROR",
]
